/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getVersion(): string
export interface JsScanResult {
  keys: Array<string>
  translations: Record<string, string>
  errors: Array<JsScanError>
  warnings: Array<JsScanWarning>
  stats: JsScanStats
}
export interface JsScanError {
  filepath: string
  line: number
  column: number
  message: string
  errorType: string
}
export interface JsScanWarning {
  filepath: string
  line: number
  column: number
  message: string
  warningType: string
}
export interface JsScanStats {
  filesScanned: number
  keysFound: number
  errorsCount: number
  warningsCount: number
  processingTimeMs: number
}
export declare function scanFilesJs(files: Array<string>): JsScanResult
export declare function scanFileJs(filepath: string): JsScanResult
